### PR TITLE
Add Location repository and location provider for android

### LINKED ISSUE #12: Create location repository
We need the location of the user. I will suggest having a location repository that uses an implementation of an locationProvider interface. Then we can create one implementation for ios and another one for Android, that uses their respective platform api for receiving user location.

### PR DESCRIPTION
**Pull request by Mkohm**
Closes #12

### CODE REVIEW

**Comment by Mkohm** [comment]
This one good to go, no? Detekt is not to happy about unimplemented methods, so should we just merge even if it fails, or do you want to create an implementation for IOSLocationProvider?

**Comment by eirikvaa** [comment]
> This one good to go, no? Detekt is not to happy about unimplemented methods, so should we just merge even if it fails, or do you want to create an implementation for IOSLocationProvider?

I'd like to look at it a bit more :)

**Comment by eirikvaa** [comment]
@Mkohm I think we should request location permissions natively and not in KMM. Haven't really figured out how to request location permissions well on iOS through KMM.

**Comment by eirikvaa** [comment]
This can be merged when #28 is merged.

**Review by eirikvaa — APPROVED** [review]
Finally 🚀

**Pull request merged**
